### ISSUE TITLE
Name report files using "mm-dd" suffixes

### ISSUE THREAD

**Issue by narqo** [LK4D4/report#2]
Do you mind if I propose a tiny improvement for the current report files naming scheme? 

For me personally, it feels much wiser to name date related files using the `%m-%d` (e.g. golang-12-08) suffixes, instead of current `%b%e` ("golang-dec8"), as it makes sorting files and searching much more natural. A general report file would be named like `golang-08-18_go17-release.md`.

What do you think about it? I believe, I can help with a PR here.

**Comment by LK4D4** [comment]
@narqo No problem, opened to any improvement. Thanks!
